// user
export const EMAIL_CHECK_REQUEST = 'EMAIL_CHECK_REQUEST'
export const EMAIL_CHECK_SUCCESS = 'EMAIL_CHECK_SUCCESS'
export const EMAIL_CHECK_FAILURE = 'EMAIL_CHECK_FAILURE'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'

// product
export const PRODUCT_SELECT_REQUEST = 'PRODUCT_SELECT_REQUEST'
export const PRODUCT_SELECT_SUCCESS = 'PRODUCT_SELECT_SUCCESS'
export const PRODUCT_SELECT_FAILURE = 'PRODUCT_SELECT_FAILURE'

export const PRODUCT_COUNT_REQUEST = 'PRODUCT_COUNT_REQUEST'
export const PRODUCT_COUNT_SUCCESS = 'PRODUCT_COUNT_SUCCESS'
export const PRODUCT_COUNT_FAILURE = 'PRODUCT_COUNT_FAILURE'
