// user
export const EMAIL_CHECK_REQUEST = 'EMAIL_CHECK_REQUEST'
export const EMAIL_CHECK_SUCCESS = 'EMAIL_CHECK_SUCCESS'
export const EMAIL_CHECK_FAILURE = 'EMAIL_CHECK_FAILURE'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'

// product
export const PRODUCT_SEARCH_REQUEST = 'PRODUCT_SEARCH_REQUEST'
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS'
export const PRODUCT_SEARCH_FAILURE = 'PRODUCT_SEARCH_FAILURE'

export const PRODUCT_SELECT_REQUEST = 'PRODUCT_SELECT_REQUEST'
export const PRODUCT_SELECT_SUCCESS = 'PRODUCT_SELECT_SUCCESS'
export const PRODUCT_SELECT_FAILURE = 'PRODUCT_SELECT_FAILURE'

export const PRODUCT_COUNT_REQUEST = 'PRODUCT_COUNT_REQUEST'
export const PRODUCT_COUNT_SUCCESS = 'PRODUCT_COUNT_SUCCESS'
export const PRODUCT_COUNT_FAILURE = 'PRODUCT_COUNT_FAILURE'

export const PRODUCT_CATEGORY_REQUEST = 'PRODUCT_CATEGORY_REQUEST'
export const PRODUCT_CATEGORY_SUCCESS = 'PRODUCT_CATEGORY_SUCCESS'
export const PRODUCT_CATEGORY_FAILURE = 'PRODUCT_CATEGORY_FAILURE'

// board
export const BOARD_SEARCH_REQUEST = 'BOARD_SEARCH_REQUEST'
export const BOARD_SEARCH_SUCCESS = 'BOARD_SEARCH_SUCCESS'
export const BOARD_SEARCH_FAILURE = 'BOARD_SEARCH_FAILURE'

export const BOARD_SELECT_REQUEST = 'BOARD_SELECT_REQUEST'
export const BOARD_SELECT_SUCCESS = 'BOARD_SELECT_SUCCESS'
export const BOARD_SELECT_FAILURE = 'BOARD_SELECT_FAILURE'

export const BOARD_ADD_REQUEST = 'BOARD_ADD_REQUEST'
export const BOARD_ADD_SUCCESS = 'BOARD_ADD_SUCCESS'
export const BOARD_ADD_FAILURE = 'BOARD_ADD_FAILURE'

// cart
export const CART_SELECT_REQUEST = 'CART_SELECT_REQUEST'
export const CART_SELECT_SUCCESS = 'CART_SELECT_SUCCESS'
export const CART_SELECT_FAILURE = 'CART_SELECT_FAILURE'

export const CART_ID_REQUEST = 'CART_ID_REQUEST'
export const CART_ID_SUCCESS = 'CART_ID_SUCCESS'
export const CART_ID_FAILURE = 'CART_ID_FAILURE'
