export const EMAIL_CHECK_REQUEST = 'EMAIL_CHECK_REQUEST'
export const EMAIL_CHECK_SUCCESS = 'EMAIL_CHECK_SUCCESS'
export const EMAIL_CHECK_FAILURE = 'EMAIL_CHECK_FAILURE'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'
